fix: only populate city/location for content types that have these fields
ValidationError: Invalid key city was thrown because the handler tried
to populate 'city' on blog-article which doesn't have that field.

Now we only populate city/location relations for content types that
actually need them (location, treatment-page, city-page).